version: '3'
services:
    ngnix:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '80:80'
        depends_on:
            - api
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
