apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "employeeapp-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /health/deep
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '2'
    alb.ingress.kubernetes.io/success-codes: 200-300
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app: employee-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "api-node-port-service"
              servicePort: 8080
